---
title: "p8105_hw2_yh3555"
author: "Yuchen Hua"
date: "2022-10-01"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE, message = FALSE)
```

```{r load_libraries}
library(tidyverse)
library(haven)
library(dplyr)
library(readxl)
library(tidyr)
```

## Problem 1

Read the dataset and retain the variables. 

```{r}
nyc_trans =
  read_csv(
    "./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv", 
    col_types = cols(Route8 = "c", Route9 = "c", Route10 = "c", Route11 = "c")) %>%
    janitor::clean_names() %>%
    select(
      line, station_name, station_latitude, station_longitude, starts_with("routes"), 
      entry, exit_only, vending, entrance_type, ada) %>%
    mutate(entry = ifelse(entry == "YES", TRUE, FALSE))
```

To find distinct stations. 
```{r}
nyc_trans %>%
  select(station_name, line) %>%
  distinct
```

To find ADA-compliant stations.
```{r}
nyc_trans %>%
  filter(ada == TRUE ) %>%
  select(station_name, line) %>%
  distinct
```

To compuate entrance/ exist without vending allowing entrance. 
```{r}
nyc_trans %>%
  filter(vending == "NO") %>%
  pull(entry) %>%
  mean
```

## Problem 2
To take a look at the the sheets in the excel file. 
```{r}
excel_sheets("./data/Trash Wheel Collection Data.xlsx")
```

```{r}
wheel_data = read_excel("./data/Trash Wheel Collection Data.xlsx", 
                        sheet = "Mr. Trash Wheel")
```

```{r}
wheel_data
```

## Problem 3
Import the data
```{r}
pols_month = 
  read_csv("./data/pols-month.csv")
```
Seperate the the columns
```{r}
separate(pols_month, col = mon, into = c('year', 'month', 'day'))
```

Clean up the the data in snp.csv
```{r}
snp = 
  read_csv("./data/snp.csv")
```



Clean up the Unemployment data
```{r}
Unemp = 
  read_csv("./data/unemployment.csv")
```





